fix memory leak in DMA pool after unloading module
Bug: When module was loaded/unloaded multiple times, following error
occurs:
rt2870: init
ERROR: 2048 KiB atomic DMA coherent pool is too small!
Please increase it with coherent_pool= kernel parameter!

How to reproduce:

for i in `seq 1 10`; do modprobe mt7601Usta && sleep 1 && rmmod
mt7601Usta && sleep 1; done

Cause: USB_URB was allocated for TX_RING_SIZE=5
but in functions
    RTMPResetTxRxRingMemory()
    RTMPFreeTxRxRingMemory()
there is magic value 4 used instead of TX_RING_SIZE